databases:
  - name: NOGAdb
    plan: free
    databaseName: nogadb_w2vx
    user: nogadb_w2vx_user

services:
  - type: web
    plan: free
    name: NOGAproject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn NOGAproject.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: NOGAdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4