# Generated by Django 5.0.6 on 2024-05-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emolyee',
            new_name='employee',
        ),
    ]
