# Generated by Django 5.0.6 on 2024-05-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('manager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='NOGAapi.employee')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='NOGAapi.city')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NOGAapi.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
