# Generated by Django 5.0.6 on 2024-05-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0002_city_branch_useremployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emolyee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='NOGAapi.employee'),
            preserve_default=False,
        ),
    ]
