# Generated by Django 5.0.4 on 2024-05-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0002_employee_id_alter_employee_national_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='job_type_id',
            new_name='job_type',
        ),
    ]
