# Generated by Django 5.0.6 on 2024-05-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0003_alter_employee_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_type',
            name='job_type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
