# Generated by Django 5.0.6 on 2024-05-31 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0004_alter_job_type_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='NOGAapi.employee'),
        ),
    ]
