# Generated by Django 5.0.6 on 2024-05-31 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0005_alter_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NOGAapi.employee'),
        ),
    ]
