# Generated by Django 5.0.6 on 2024-06-06 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0007_alter_branch_city_alter_branch_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(default=1313, on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.city'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manager_of_branch', to='NOGAapi.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.job_type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.employee'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.employee'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
