# Generated by Django 5.0.6 on 2024-07-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0011_accessories_categories_color_cpu_phone_brands_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEmployee',
            new_name='User_Employee',
        ),
    ]
