# Generated by Django 5.0.6 on 2024-07-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0013_rename_color_phone_color_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='CPU_brand',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='phone_brands',
            name='brand_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
