# Generated by Django 5.0.6 on 2024-07-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0014_alter_color_color_alter_cpu_cpu_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessories',
            new_name='Accessory',
        ),
        migrations.RenameModel(
            old_name='Accessories_Categories',
            new_name='Accessory_Category',
        ),
        migrations.RenameModel(
            old_name='Phone_Brands',
            new_name='Phone_Brand',
        ),
        migrations.RenameModel(
            old_name='Phone_Accessories',
            new_name='Phones_Accessories',
        ),
    ]
