# Generated by Django 5.0.6 on 2024-07-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0015_rename_accessories_accessory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory_category',
            name='category_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
