# Generated by Django 5.0.6 on 2024-07-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0016_alter_accessory_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOGAapi.city'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_of_branch', to='NOGAapi.employee'),
        ),
    ]
