# Generated by Django 5.0.6 on 2024-07-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0017_alter_branch_city_alter_branch_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='NOGAapi.city'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='manager_of_branch', to='NOGAapi.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='NOGAapi.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='NOGAapi.job_type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='NOGAapi.employee'),
        ),
    ]
