# Generated by Django 5.0.6 on 2024-07-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0020_alter_branch_city_alter_branch_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_process', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Entered_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('wholesale_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NOGAapi.product')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOGAapi.entry_process')),
            ],
        ),
    ]
