# Generated by Django 5.0.6 on 2024-07-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0022_alter_entered_product_selling_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.branch')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='Products_Movment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_process', models.DateField()),
                ('movement_type', models.BooleanField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Transported_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholesale_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOGAapi.products_movment')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.product')),
            ],
        ),
    ]
