# Generated by Django 5.0.6 on 2024-07-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0023_branch_products_products_movment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transported_Products',
            new_name='Transported_Product',
        ),
    ]
