# Generated by Django 5.0.6 on 2024-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0025_rename_product_id_accessory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.FileField(null=True, upload_to='QR/'),
        ),
    ]
