# Generated by Django 5.0.6 on 2024-07-30 19:10

import NOGAapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0026_product_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=NOGAapi.models.upload_to),
        ),
    ]
