# Generated by Django 5.0.6 on 2024-07-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0027_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
