# Generated by Django 5.0.6 on 2024-07-31 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0028_alter_product_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='entry_process',
            name='date_of_process',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products_movment',
            name='date_of_process',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Branches_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', models.DateField(auto_now_add=True)),
                ('note', models.CharField(max_length=150, null=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOGAapi.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField(auto_now_add=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.branch')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholesale_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('purchased_quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NOGAapi.product')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOGAapi.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Requested_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOGAapi.product')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOGAapi.branches_requests')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOGAapi.request_status')),
            ],
        ),
    ]
