# Generated by Django 5.0.6 on 2024-07-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0029_request_status_alter_entry_process_date_of_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_products',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='entered_product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='purchased_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requested_products',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transported_product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
