# Generated by Django 5.0.6 on 2024-07-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOGAapi', '0030_alter_branch_products_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_codes_download',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
